Repository Mujtabaa07/coffeeShop, pull requests merged in 2025-07, with the labels that each got.

#459 Fav Added
  package-lock.json
  src/App.js
  src/Pages/Shop.js
  src/Pages/cake.js
  src/Pages/coffee.js
  src/Pages/favorites.js
  src/Pages/hooks/useFavorites.js
  src/Pages/profile.js
  src/componets/Dropdown.css
  src/componets/Dropdown.js
  src/componets/Navitems.js
  src/componets/ScrollToTop.js
  src/index.js
Labels: INTERMEDIATE, GSSoC'25

#465 Fixed the scrolling navigation of buttons to respective sections
  src/Pages/Shop.js
Labels: BEGINNER, GSSoC'25

#453 Fix Scroll-to-Top Button Runtime Error by Moving Logic into React Component
  src/componets/ScrollToTop.js
  src/index.js
Labels: bug, INTERMEDIATE, GSSoC'25

#452 bug is fixed
  src/Pages/Home.css
  src/componets/Button.js
  src/componets/Dropdown.js
Labels: INTERMEDIATE, GSSoC'25

#480 added missed images in Hot Beverage Section
  src/Pages/Shop.js
Labels: BEGINNER, GSSoC'25
