Repository Mujtabaa07/coffeeShop, pull requests merged in 2025-02, with the labels that each got.

#358 Elevate the "Our Cake Selection" Page with Flawless Heading Alignment 🎂✨
  src/Pages/cake.js
Labels: SWOC, BEGINNER

#392 Fix : Navbar Alignment and Navbar Responsiveness for Medium Devices
  src/componets/Navbar.css
  src/componets/Navbar.js
Labels: SWOC, INTERMEDIATE

#393 removed unusual scrolling of the pages
  package-lock.json
  src/componets/ScrollToTop.js
Labels: SWOC, INTERMEDIATE

#394 removed duplicate text
  src/Pages/cake.js
Labels: SWOC, BEGINNER

#398 Aligned payment options in footer section
  src/componets/footer.js
Labels: SWOC, BEGINNER

#400 added blog page
  src/App.js
  src/Pages/blog.js
  src/Pages/blog1.js
  src/Pages/blog2.js
  src/Pages/blog3.js
  src/componets/footer.js
Labels: SWOC, ADVANCE

#403 Made Testimonial responsive for smaller screens
  src/Pages/Testimonial.css
Labels: SWOC, BEGINNER

#405 Added star icons in Feedback Page
  package-lock.json
  package.json
  src/Pages/Feedback.js
  src/Pages/StarRating.css
  src/Pages/StarRating.js
Labels: SWOC, INTERMEDIATE

#406 Locked scroll on mobile devices when hamburger menu is opened
  src/componets/Navbar.js
Labels: SWOC, INTERMEDIATE

#410 Fixed responsiveness on premium beans page
  src/Pages/PremiumBeans.js
Labels: SWOC, BEGINNER

#417 Updated twitter icon to X
  src/componets/footer.js
Labels: SWOC, BEGINNER

#419 Create `LICENSE`
  LICENSE
Labels: SWOC, BEGINNER

#420 added hover effect on payment icons
  src/componets/footer.js
Labels: SWOC, BEGINNER

#423 Fix #415 Link-social-media
  src/componets/footer.js
Labels: SWOC, BEGINNER

#424 added path to cozy ambience
  src/Pages/Home.js
Labels: SWOC, BEGINNER

#430 Improved Login Page's Responsiveness
  src/Pages/login.js
Labels: SWOC, INTERMEDIATE

#431 Improved Register Page's Responsiveness
  src/Pages/Register.js
Labels: SWOC, INTERMEDIATE

#433 Images with watermarks changed
  src/Pages/Home.js
  src/Pages/Shop.js
Labels: SWOC, INTERMEDIATE

#434 enhanced UI of contact us page
  src/App.css
  src/Pages/contact.js
Labels: SWOC, INTERMEDIATE

#435 enhanced UI of cake page
  src/Pages/cake.js
Labels: SWOC, BEGINNER

#438 Added 3d hover effect to the all review cards
  src/componets/Reviews.js
Labels: SWOC, INTERMEDIATE

#437 Footer items alignment fix
  src/componets/footer.js
Labels: SWOC, BEGINNER
