Repository Mujtabaa07/coffeeShop, pull requests merged in 2025-01, with the labels that each got.

#66 🛠️FIX : Contact us page name field validation added
  src/Pages/contact.js
Labels: SWOC, BEGINNER

#76 Fix: Misalignment of Headings from Testimonials and About Us pages
  src/Pages/Testimonial.css
  src/Pages/Testimonial.js
  src/Pages/contact.js
Labels: SWOC, BEGINNER

#78 Fixed and Improved the css of Card #12
  src/Pages/Shop.js
Labels: SWOC, INTERMEDIATE

#96 Fixed hamburger menu for small screen devices
  src/componets/Navbar.js
Labels: SWOC, BEGINNER

#82 Added hover effect on testimonials cards
  src/Pages/Testimonial.css
Labels: SWOC, BEGINNER

#86 updated scroll button to the home page
  package-lock.json
  package.json
  public/index.html
  src/index.css
  src/index.js
Labels: enhancement, SWOC, INTERMEDIATE

#88 Dockerize Container
  Dockerfile
  nginx.conf
Labels: SWOC, ADVANCE

#90 Fix the css of Card
  src/Pages/Home.css
  src/Pages/Home.js
  src/Pages/Shop.js
  src/componets/Button.js
Labels: bug, SWOC, BEGINNER

#106 navbar visibility on smaller screen fixed
  src/componets/Navbar.css
Labels: bug, SWOC, BEGINNER

#112 Active current page in nav bar
  src/componets/Navbar.css
  src/componets/Navbar.js
Labels: SWOC, BEGINNER

#115 Update README.md
  README.md
Labels: SWOC, BEGINNER

#117 updated testimonial styling
  src/Pages/Testimonial.css
  src/Pages/Testimonial.js
Labels: SWOC, BEGINNER

#118 Add premium beans
  package-lock.json
  src/App.js
  src/Pages/Home.js
  src/Pages/PremiumBeans.js
  src/componets/Navbar.js
Labels: SWOC, INTERMEDIATE

#152 Added a 'Register' button to the navbar and drop-down menu that directly navigates to the sign-up page.
  README.md
  package-lock.json
  src/componets/Navbar.js
Labels: SWOC, INTERMEDIATE

#143 Fix Navbar and Checkout Heading Overlap Issue
  src/Pages/checkOut.js
Labels: bug, SWOC, BEGINNER

#121 Replaced second 'Add to Cart' button with 'Buy Now' button
  package-lock.json
  src/Pages/Shop.js
  src/componets/Button.js
Labels: SWOC, ADVANCE

#139 Added Hover Scale Effect to Input Fields
  package-lock.json
  src/Pages/contact.js
Labels: SWOC, BEGINNER

#138 Enhanced Testimonial Pages
  src/Pages/Testimonial.css
  src/Pages/Testimonial.js
Labels: enhancement, SWOC, BEGINNER

#156 #18 top reviews
  src/App.js
  src/componets/Reviews.js
Labels: enhancement, SWOC, INTERMEDIATE

#140 Forget Password feature added
  package-lock.json
  package.json
  src/App.js
  src/Pages/ForgetPassword.js
  src/Pages/login.js
Labels: enhancement, SWOC, INTERMEDIATE

#135 updated the shop page button
  src/Pages/Shop.js
  src/componets/Button.js
Labels: SWOC, BEGINNER

#131 Updated Profile page UI
  src/Pages/profile.js
Labels: bug, SWOC, BEGINNER

#166 Improved the registeration form ui
  package-lock.json
  package.json
  src/Pages/Register.js
Labels: enhancement, SWOC, INTERMEDIATE

#164 a very minor change in README.md near usage section
  README.md
Labels: documentation, SWOC, BEGINNER

#177 Updated the Navbar
  src/componets/Navbar.js
Labels: SWOC, BEGINNER

#176 Added Scroll-To-Top feature to the website-175
  src/App.js
  src/componets/ScrollToTop.js
Labels: SWOC, BEGINNER

#163 Enhance Register Form Design
  src/Pages/Register.js
Labels: SWOC, INTERMEDIATE

#178 Change Images
  src/Pages/Home.js
  src/Pages/PremiumBeans.js
  src/Pages/Shop.js
Labels: SWOC, BEGINNER

#182 enhance login page
  src/Pages/login.js
Labels: enhancement, SWOC, INTERMEDIATE

#192 fixing navlink alignment
  package-lock.json
  src/componets/Navbar.css
  src/componets/footer.js
Labels: SWOC, BEGINNER

#187 contact page updated
  src/Pages/contact.js
Labels: SWOC, INTERMEDIATE

#185 Proper FAQ Section with proper JS functionality #162
  src/App.js
  src/Pages/Home.js
  src/componets/faq.css
  src/componets/faq.js
Labels: enhancement, SWOC, INTERMEDIATE

#199 making responsive to all Navlink pages like testinomials, Expert Baristas
  src/Pages/ExpertBaristas.js
  src/Pages/PremiumBeans.js
  src/Pages/Testimonial.css
  src/Store/cartSlice.js
  src/componets/Navbar.css
  src/componets/Navbar.js
Labels: SWOC, INTERMEDIATE

#221 #181 premium beans page
  src/Pages/PremiumBeans.js
Labels: enhancement, SWOC, BEGINNER

#212 Issue #198 Resolved: Register Validation
  src/Pages/Register.js
Labels: SWOC, BEGINNER

#234 updated the arrow and coffee scroll positions and updated padding of …
  src/Pages/Home.js
Labels: bug, SWOC, BEGINNER

#232 Realigned the Titles for Shop, About and Contact Sections
  src/Pages/About.js
  src/Pages/Shop.js
  src/Pages/contact.js
Labels: bug, SWOC, BEGINNER

#230 MODIFY NAVBAR add dropdown menu #issue-200
  src/componets/Dropdown.css
  src/componets/Dropdown.js
  src/componets/Navbar.css
  src/componets/Navbar.js
  src/componets/Navitems.js
Labels: SWOC, BEGINNER

#228 Fixed width issue of Home page #208 and NEW [FEATURE] #209 load more button in shop page
  src/Pages/Home.js
  src/Pages/Shop.js
Labels: SWOC, BEGINNER

#225 enhanced about page
  src/Pages/About.js
Labels: SWOC, BEGINNER

#218 Redesigned the FAQ section present in Homepage
  src/componets/faq.js
Labels: SWOC, BEGINNER

#242 Improved shop section
  src/Pages/Shop.js
Labels: SWOC, INTERMEDIATE

#222 Hovering animation on the cards on the Home page #149
  src/Pages/Home.js
Labels: SWOC, BEGINNER

#269 remove unused and extra home menu and improve code
  src/componets/Navbar.js
  src/componets/Navitems.js
Labels: SWOC, BEGINNER

#267 266: Add Background image to Forget Password Page
  src/Pages/ForgetPassword.js
Labels: SWOC, BEGINNER

#261 removed the Unnecessary read more button
  src/Pages/ExpertBaristas.js
Labels: SWOC, BEGINNER

#254 Issue 74 - Updation of Read Me Completed
  README.md
Labels: SWOC, BEGINNER

#245 🔗fix: Update README.md
  README.md
Labels: SWOC, BEGINNER

#285 #268 - bug fix and style
  src/Pages/cake.js
  src/Pages/coffee.js
  src/Pages/milkshake.js
  src/Pages/soup.js
Labels: SWOC, INTERMEDIATE

#280 created FAQ Page
  package-lock.json
  src/App.js
  src/Pages/Faq.js
  src/Pages/Home.js
  src/componets/Navbar.js
Labels: SWOC, BEGINNER

#275 enhanced contact us page
  package-lock.json
  src/Pages/contact.js
  src/componets/Button.js
Labels: SWOC, BEGINNER

#273 [BUG] Profile Page is not visible #116
  src/Pages/profile.js
Labels: SWOC, INTERMEDIATE

#272 Enhance footer component with quick links and update social media icons
  src/Pages/Home.js
  src/componets/footer.js
Labels: SWOC, BEGINNER

#247 Modified AboutUs.js
  src/Pages/About.js
  src/Pages/Shop.js
Labels: SWOC, BEGINNER

#257 [FIX] Typo and inconsistent capitalization on "Expert Baristas" on navbar's Product drop-down option
  src/componets/Navitems.js
Labels: SWOC, BEGINNER

#289 updating the add button and shop button
  src/Pages/cake.js
  src/componets/Button.js
Labels: SWOC, BEGINNER

#287 [FEATURE]: Quantity Control for cart items, Payment receipt & proceeding option, Improved UI/UX for product pages
  src/Pages/Shop.js
  src/Pages/cake.js
  src/Pages/cart.js
  src/Pages/coffee.js
  src/Pages/milkshake.js
  src/Pages/soup.js
Labels: SWOC, ADVANCE

#271 Remove extra User link from Navbar
  src/componets/Navbar.js
Labels: SWOC, BEGINNER

#251 Did a couple of changes. Updated the styling.
  package-lock.json
  package.json
  src/Pages/Shop.js
  src/Pages/cake.js
Labels: SWOC, INTERMEDIATE

#244 Flash message added on clicking add to cart button
  package-lock.json
  package.json
  src/App.js
  src/Pages/Shop.js
  src/Pages/cart.js
Labels: SWOC, INTERMEDIATE

#298 #235 fixed UI added Dynamic Text and a coffee Pre-loader -> to make it more interactive
  package-lock.json
  package.json
  public/index.html
  src/Pages/Home.css
  src/Pages/Home.js
  src/Pages/dynamicText.js
Labels: SWOC, ADVANCE

#294 added chat with coffee expert
  package-lock.json
  package.json
  src/Pages/ExpertBaristas.js
Labels: SWOC, ADVANCE

#292 Image Alignment of the testimonials is fixed #124
  package.json
Labels: SWOC, BEGINNER

#318 search button added
  package-lock.json
  src/Pages/Shop.js
  src/Pages/cake.js
  src/Pages/coffee.js
  src/Pages/milkshake.js
  src/Pages/soup.js
Labels: SWOC, INTERMEDIATE

#313 Added About to navbar
  src/componets/Navbar.css
  src/componets/Navbar.js
  src/componets/Navitems.js
Labels: SWOC, BEGINNER

#310 Added about section in navbar
  src/componets/Navbar.js
  src/componets/Navitems.js
Labels: SWOC, BEGINNER

#304 Added and updated the Footer Icons
  src/componets/footer.js
Labels: SWOC, BEGINNER

#297 Bug Fix for Premium Beans Responsive UI - Fixed the Cards moving out of frame
  src/Pages/PremiumBeans.js
Labels: SWOC, INTERMEDIATE

#323 Fixed Mistake
  src/componets/Navitems.js
Labels: SWOC, BEGINNER

#317 Added heart icon to all the cards of the products
  package-lock.json
  package.json
  src/Pages/Shop.js
  src/Pages/cake.js
  src/Pages/coffee.js
  src/Pages/milkshake.js
  src/Pages/soup.js
Labels: SWOC, ADVANCE

#324 Footer UI Update
  src/componets/footer.js
Labels: SWOC, BEGINNER

#325 hover effect on social media icons
  src/componets/footer.js
Labels: SWOC, BEGINNER

#329 fixed arrow in faq
  package-lock.json
  package.json
  src/Pages/Faq.js
  src/componets/faq.js
Labels: SWOC, INTERMEDIATE

#331 Login/Register Page UI updated
  src/Pages/Register.js
  src/Pages/login.js
Labels: SWOC, INTERMEDIATE

#333 Add footer image and colour enhancement
  src/componets/FooterImg.png
  src/componets/footer.js
Labels: SWOC, INTERMEDIATE

#335 🛠️ Feat : Github Actions added
  .github/workflows/auto-comment.yml
Labels: SWOC, INTERMEDIATE

#336 Proper alignment of navbar options
  src/componets/Navbar.js
Labels: SWOC, BEGINNER

#337 [Feature]: Redesigned "Our specialties" section, added navigation and removed unwanted elements in navbar
  src/Pages/Home.js
  src/Pages/cake.js
  src/Pages/milkshake.js
  src/Pages/soup.js
  src/componets/Navbar.js
  src/componets/Navitems.js
Labels: SWOC, INTERMEDIATE

#340 in shop made the search button from rectangle shape to rounder corners add some margin form right to deattch the search icon , also made changes in the search icon also.
  src/Pages/Shop.js
Labels: SWOC, BEGINNER

#341 Update Navitems.js
  src/componets/Navitems.js
Labels: SWOC, BEGINNER

#296 Update Testimonial.js
  src/Pages/Testimonial.js
Labels: SWOC, BEGINNER

#351 Added terms and conditions
  src/App.js
  src/Pages/Register.js
  src/Pages/Terms.js
Labels: SWOC, INTERMEDIATE

#350 Issue 320 update
  src/App.js
  src/Pages/contributor.js
  src/componets/Navitems.js
  src/componets/footer.js
Labels: SWOC, ADVANCE

#348 added links to email and phone
  src/componets/footer.js
Labels: SWOC, BEGINNER

#352 fixed image hover effect
  src/Pages/About.js
Labels: SWOC, BEGINNER

#353 🔧✨ Fixed Footer Section: Enhanced Social Icon UI/UX
  src/componets/footer.js
Labels: SWOC, BEGINNER

#356 added custom cursor
  package-lock.json
  package.json
  src/App.js
Labels: SWOC, INTERMEDIATE

#355 Changes in footer for responsive footer content
  src/componets/footer.js
Labels: SWOC, BEGINNER

#361 UI enhancement of Products
  src/Pages/PremiumBeans.js
Labels: SWOC, INTERMEDIATE

#364 enhanced testimonial page
  src/Pages/Testimonial.css
  src/Pages/Testimonial.js
Labels: SWOC, BEGINNER

#365 added feedback page
  src/App.js
  src/Pages/Feedback.css
  src/Pages/Feedback.js
  src/componets/Navbar.js
  src/componets/Navitems.js
Labels: SWOC, INTERMEDIATE

#366 Payment Options Not Displayed #357
  src/componets/footer.js
Labels: SWOC, BEGINNER

#387 Implement Responsive Button behavior in shop.js
  src/Pages/Shop.js
Labels: SWOC, INTERMEDIATE

#377 #367- styled barista page
  src/Pages/ExpertBaristas.js
Labels: SWOC, ADVANCE

#372 Added Twitter and Github icons' native colors while hovering over them at footer
  src/componets/footer.js
Labels: SWOC, BEGINNER

#227 Add cozyAmbiance page
  package-lock.json
  src/App.js
  src/Pages/CozyAmbiance.css
  src/Pages/CozyAmbiance.js
  src/Pages/PremiumBeans.js
  src/Pages/Shop.js
  src/Pages/cake.js
  src/Pages/coffee.js
  src/Pages/milkshake.js
  src/Pages/profile.js
  src/Pages/soup.js
  src/componets/Dropdown.css
  src/componets/Dropdown.js
  src/componets/Navbar.css
  src/componets/Navbar.js
  src/componets/Navitems.js
  src/componets/footer.js
Labels: SWOC, ADVANCE

#382 Text Submerged
  src/Pages/Home.js
Labels: SWOC, BEGINNER
